import type { Career, CareerClusterMeta, CareerCluster } from '@/types/career';

export const CLUSTER_META: Record<CareerCluster, CareerClusterMeta> = {
  tech: { label: 'Technology', color: '#818cf8', iconName: 'Cpu' },
  creative: { label: 'Creative', color: '#f472b6', iconName: 'Palette' },
  business: { label: 'Business', color: '#fb923c', iconName: 'TrendingUp' },
  science: { label: 'Science', color: '#34d399', iconName: 'FlaskConical' },
  health: { label: 'Healthcare', color: '#f87171', iconName: 'HeartPulse' },
  education: { label: 'Education', color: '#fbbf24', iconName: 'GraduationCap' },
};

export const CAREERS: Career[] = [
  {
    id: 'software-engineer',
    title: 'Software Engineer',
    cluster: 'tech',
    color: '#818cf8',
    description: 'Build the systems and products that power the modern world.',
    salary: { entry: 75000, mid: 110000, senior: 160000 },
    skills: ['Problem Solving', 'System Design', 'Algorithms', 'Collaboration'],
    education: 'CS degree or bootcamp',
    growthRate: '+25% by 2030',
    dayInLife: 'Design, code, review, and ship features in a collaborative team.',
    relatedTo: ['ux-designer', 'data-scientist', 'product-manager', 'cybersecurity-analyst'],
    iconName: 'Code2',
  },
  {
    id: 'ux-designer',
    title: 'UX Designer',
    cluster: 'creative',
    color: '#f472b6',
    description: 'Shape how millions of people interact with technology.',
    salary: { entry: 60000, mid: 90000, senior: 130000 },
    skills: ['Empathy', 'Visual Design', 'Prototyping', 'User Research'],
    education: 'Design degree or portfolio',
    growthRate: '+16% by 2030',
    dayInLife: 'Research user needs, sketch flows, prototype interfaces, and test solutions.',
    relatedTo: ['software-engineer', 'product-manager', 'graphic-designer'],
    iconName: 'Layers',
  },
  {
    id: 'data-scientist',
    title: 'Data Scientist',
    cluster: 'tech',
    color: '#818cf8',
    description: 'Extract insight from data to drive billion-dollar decisions.',
    salary: { entry: 80000, mid: 120000, senior: 180000 },
    skills: ['Statistics', 'Machine Learning', 'Python', 'Communication'],
    education: 'Statistics or CS degree',
    growthRate: '+36% by 2030',
    dayInLife: 'Clean datasets, build predictive models, and present findings to leadership.',
    relatedTo: ['software-engineer', 'financial-analyst', 'biomedical-engineer'],
    iconName: 'BarChart3',
  },
  {
    id: 'product-manager',
    title: 'Product Manager',
    cluster: 'business',
    color: '#fb923c',
    description: 'Lead cross-functional teams to ship products users love.',
    salary: { entry: 85000, mid: 130000, senior: 200000 },
    skills: ['Strategy', 'Communication', 'Prioritization', 'Empathy'],
    education: 'Business or any technical degree',
    growthRate: '+10% by 2030',
    dayInLife: 'Define product vision, coordinate engineers and designers, remove blockers.',
    relatedTo: ['software-engineer', 'ux-designer', 'data-scientist'],
    iconName: 'Target',
  },
  {
    id: 'biomedical-engineer',
    title: 'Biomedical Engineer',
    cluster: 'science',
    color: '#34d399',
    description: 'Design technology that saves lives at the intersection of medicine and engineering.',
    salary: { entry: 60000, mid: 95000, senior: 140000 },
    skills: ['Biology', 'Engineering', 'Critical Thinking', 'Research'],
    education: 'Biomedical Engineering degree',
    growthRate: '+10% by 2030',
    dayInLife: 'Design medical devices, run clinical tests, and collaborate with surgeons.',
    relatedTo: ['doctor', 'data-scientist', 'environmental-scientist'],
    iconName: 'Activity',
  },
  {
    id: 'graphic-designer',
    title: 'Graphic Designer',
    cluster: 'creative',
    color: '#f472b6',
    description: 'Communicate ideas visually — from brand identity to digital campaigns.',
    salary: { entry: 45000, mid: 65000, senior: 95000 },
    skills: ['Visual Thinking', 'Typography', 'Color Theory', 'Adobe Suite'],
    education: 'Design degree or strong portfolio',
    growthRate: '+3% by 2030',
    dayInLife: 'Design brand materials, collaborate with marketing, and iterate on feedback.',
    relatedTo: ['ux-designer', 'architect', 'product-manager'],
    iconName: 'PenTool',
  },
  {
    id: 'financial-analyst',
    title: 'Financial Analyst',
    cluster: 'business',
    color: '#fb923c',
    description: 'Translate numbers into strategy for corporations and investors.',
    salary: { entry: 60000, mid: 90000, senior: 140000 },
    skills: ['Financial Modeling', 'Excel/SQL', 'Critical Thinking', 'Communication'],
    education: 'Finance or Economics degree',
    growthRate: '+9% by 2030',
    dayInLife: 'Build financial models, analyze market trends, and present investment cases.',
    relatedTo: ['product-manager', 'data-scientist'],
    iconName: 'DollarSign',
  },
  {
    id: 'doctor',
    title: 'Physician',
    cluster: 'health',
    color: '#f87171',
    description: 'Diagnose, treat, and transform patients\' lives with expertise and compassion.',
    salary: { entry: 80000, mid: 200000, senior: '300K+' },
    skills: ['Medical Knowledge', 'Empathy', 'Decision-making', 'Communication'],
    education: 'Medical degree (MD/DO)',
    growthRate: '+3% by 2030',
    dayInLife: 'Examine patients, diagnose conditions, prescribe treatment, and coordinate care.',
    relatedTo: ['biomedical-engineer', 'teacher'],
    iconName: 'Stethoscope',
  },
  {
    id: 'teacher',
    title: 'Educator',
    cluster: 'education',
    color: '#fbbf24',
    description: 'Shape the next generation through inspiring, evidence-based teaching.',
    salary: { entry: 40000, mid: 58000, senior: 80000 },
    skills: ['Communication', 'Patience', 'Curriculum Design', 'Mentorship'],
    education: 'Education degree + certification',
    growthRate: '+5% by 2030',
    dayInLife: 'Plan lessons, engage students, provide feedback, and foster curiosity.',
    relatedTo: ['doctor', 'environmental-scientist'],
    iconName: 'BookOpen',
  },
  {
    id: 'environmental-scientist',
    title: 'Environmental Scientist',
    cluster: 'science',
    color: '#34d399',
    description: 'Protect ecosystems and drive sustainability policy with data.',
    salary: { entry: 48000, mid: 73000, senior: 105000 },
    skills: ['Field Research', 'Data Analysis', 'Environmental Law', 'Report Writing'],
    education: 'Environmental Science degree',
    growthRate: '+8% by 2030',
    dayInLife: 'Collect samples, analyze environmental data, write policy reports.',
    relatedTo: ['biomedical-engineer', 'teacher', 'data-scientist'],
    iconName: 'Leaf',
  },
  {
    id: 'cybersecurity-analyst',
    title: 'Cybersecurity Analyst',
    cluster: 'tech',
    color: '#818cf8',
    description: 'Defend systems from hackers and build resilient digital infrastructure.',
    salary: { entry: 70000, mid: 105000, senior: 155000 },
    skills: ['Network Security', 'Threat Analysis', 'Ethical Hacking', 'Risk Assessment'],
    education: 'CS or Cybersecurity degree + certs',
    growthRate: '+35% by 2030',
    dayInLife: 'Monitor threats, run penetration tests, incident response, and harden systems.',
    relatedTo: ['software-engineer', 'data-scientist'],
    iconName: 'ShieldCheck',
  },
  {
    id: 'architect',
    title: 'Architect',
    cluster: 'creative',
    color: '#f472b6',
    description: 'Design spaces that shape how people live, work, and experience the world.',
    salary: { entry: 52000, mid: 82000, senior: 120000 },
    skills: ['Spatial Thinking', 'CAD Software', 'Structural Knowledge', 'Creativity'],
    education: 'Architecture degree (5+ years)',
    growthRate: '+5% by 2030',
    dayInLife: 'Draft blueprints, collaborate with clients, manage construction phases.',
    relatedTo: ['graphic-designer', 'environmental-scientist'],
    iconName: 'Building2',
  },
];

export function getCareerById(id: string): Career | undefined {
  return CAREERS.find((c) => c.id === id);
}

export function getCareersByCluster(cluster: string): Career[] {
  return CAREERS.filter((c) => c.cluster === cluster);
}

export function formatSalary(amount: number | string): string {
  if (typeof amount === 'string') return amount;
  return `$${(amount / 1000).toFixed(0)}K`;
}
